# Generated by Django 5.2.11 on 2026-02-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_person_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_walkins',
            field=models.BooleanField(default=False, help_text='Allow check-in for people not pre-registered'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
