# Generated by Django 5.2.11 on 2026-02-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_event_allow_walkins_alter_person_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="reg_close",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="reg_open",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
