# Generated by Django 5.2.12 on 2026-03-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_reg_open_reg_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
