# Generated by Django 5.2.11 on 2026-03-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_event_reg_close_event_reg_open"),
        ("core", "0005_event_external_link"),
    ]

    operations = []
