# Generated by Django 5.2.11 on 2026-03-24 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_merge_20260324_1315"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="reg_close",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="reg_open",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
