# Generated by Django 5.2.11 on 2026-04-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_eventreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Notification settings, e.g. {"event_reminders": true, "event_updates": true, "new_events": true}'),
        ),
    ]
