# Generated by Django 5.2.11 on 2026-04-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_person_notification_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='disable_gui_registration',
            field=models.BooleanField(default=False, help_text='Hide web registration button; only API/external registration allowed'),
        ),
    ]
