# Generated by Django 5.2.11 on 2026-04-09 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event_disable_gui_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed — attendee said yes'), ('denied', 'Denied — attendee said no'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='core.scanlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
