# Generated by Django 5.2.11 on 2026-04-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.TextField(blank=True, default='', help_text='Base64-encoded profile image data URI'),
        ),
    ]
