# Generated by Django 5.2.11 on 2026-04-13 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_person_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='card_color',
            field=models.CharField(blank=True, choices=[('rose', 'Rose'), ('lavender', 'Lavender'), ('mint', 'Mint'), ('peach', 'Peach'), ('sky', 'Sky'), ('lemon', 'Lemon')], default='peach', max_length=20),
        ),
        migrations.CreateModel(
            name='ScannedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scanned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_by', to='core.person')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_contacts', to='core.person')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('scanner', 'scanned')},
            },
        ),
    ]
