# Generated by Django 5.2.11 on 2026-04-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_person_card_color_scannedcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='event_limit',
            field=models.PositiveSmallIntegerField(default=10, help_text='Max active events this user may have at once (0 = unlimited)'),
        ),
    ]
